name: portfolio ci/dc

on:
  push:
    branches:
      - develop

jobs:
  checkout:
    name: checkout
    runs-on: [runner-1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  build:
    name: build
    needs: checkout
    runs-on: [runner-1]

    steps:
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: install dependencies
        run: npm install

      - name: build project
        run: npm run build

      - name: change static build files
        run: |
          rm -rf /opt/deploy/portfolio 
          cp -r ./dist /opt/deploy/portfolio
